/**
 * The publication's mark, for images Next generates at request time.
 *
 * icon, apple-icon and both opengraph-image routes used to each carry their own
 * copy of a red tile with a stock bolt path in it. Three copies of a logo is
 * three logos: the next edit lands in one of them and the set quietly drifts.
 * This is the single definition they all draw from.
 *
 * The geometry is the same 64-unit square the SVG masters and the PNG build
 * script use, so the generated images and the exported files stay identical:
 *   ../../intokened.com/build-logo.py
 *
 * Deliberately flat gold rather than the folded two-plane gradient of the full
 * mark. These images render through Satori, whose SVG gradient support is
 * partial, and every place this component appears is small enough that the fold
 * would read as noise anyway — the same reason the 16px favicon is flat.
 */

/**
 * Corner brackets: four right angles, each two rounded capsules.
 *
 * Rectangles with a radius rather than a stroked path — Satori renders these
 * images, and its rounded-rect support is complete where its stroke support is
 * not. The same eight numbers draw the header mark and every exported PNG.
 *
 * Generated by ../../intokened.com/build-logo.py; regenerate rather than edit.
 */
const CAPSULES: ReadonlyArray<readonly [number, number, number, number]> = [
  [10.25, 9.25, 8.5, 3.5], [10.25, 9.25, 3.5, 8.5],
  [45.25, 9.25, 8.5, 3.5], [50.25, 9.25, 3.5, 8.5],
  [10.25, 51.25, 8.5, 3.5], [10.25, 46.25, 3.5, 8.5],
  [45.25, 51.25, 8.5, 3.5], [50.25, 46.25, 3.5, 8.5],
];
const CAPSULE_R = 1.75;

/** Cut to the drawing rather than the unit square — see BrandMarkSvg. */
const VIEW_BOX = '9.5 8.5 45 47';
/** 45:47. Callers pass a size; the mark keeps its own proportion inside it. */
const ASPECT = 45 / 47;

/** The bolt, already scaled to 0.66 and centred — the value the brackets frame. */
const BOLT = '37.28,14.84 21.44,34.64 30.68,34.64 26.72,49.16 42.56,29.36 33.32,29.36';

export const BRAND_GRAPHITE = '#1d1d1f';
export const BRAND_PAPER = '#f2f3f5';
export const BRAND_GOLD = '#ffc93c';

/**
 * Below this the gap between a bracket and the bolt falls under a pixel and the
 * mark collapses into a blob, so the brackets come off and the bolt fills the
 * frame instead. Matches the threshold in the PNG build script.
 */
const BRACKET_FLOOR = 48;

export function BrandMark({
  size,
  bracket = BRAND_PAPER,
  bolt = BRAND_GOLD,
  simplified,
}: {
  size: number;
  bracket?: string;
  bolt?: string;
  /**
   * Overrides the size threshold. Pass `false` where the drawing is small in
   * its own coordinate space but large on screen — the badge on a 1200×630
   * social card is 35 units wide and displayed at several times that, so the
   * automatic rule would strip the brackets from an image nobody sees small.
   */
  simplified?: boolean;
}) {
  if (simplified ?? size < BRACKET_FLOOR) {
    return (
      <svg width={size} height={size} viewBox="0 0 64 64">
        <polygon points="40,6 16,36 30,36 24,58 48,28 34,28" fill={bolt} />
      </svg>
    );
  }
  // `size` is the height; the width follows the mark's own 45:47, so the
  // drawing keeps its proportion instead of being stretched into a square.
  return (
    <svg width={Math.round(size * ASPECT)} height={size} viewBox={VIEW_BOX}>
      {CAPSULES.map(([x, y, w, h]) => (
        <rect key={`${x}-${y}-${w}`} x={x} y={y} width={w} height={h} rx={CAPSULE_R} fill={bracket} />
      ))}
      <polygon points={BOLT} fill={bolt} />
    </svg>
  );
}

/** The mark on its graphite tile — the form used as an app icon or avatar. */
export function BrandTile({
  size,
  radius,
  simplified,
}: {
  size: number;
  radius?: number;
  simplified?: boolean;
}) {
  return (
    <div
      style={{
        width: size,
        height: size,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: BRAND_GRAPHITE,
        borderRadius: radius ?? Math.round(size * 0.22),
      }}
    >
      <BrandMark size={Math.round(size * 0.62)} simplified={simplified} />
    </div>
  );
}
