// GENERATED by scripts/gen-page-revisions.mjs — do not edit by hand.
// Last commit date of each hand-authored page's source, used as its sitemap
// lastmod. Regenerate after editing any of these pages:
//   node scripts/gen-page-revisions.mjs

export const PAGE_REVISIONS: Record<string, string> = {
  '/calculators': '2026-08-11',
  '/calculators/wealth': '2026-07-30',
  '/calculators/converter': '2026-08-10',
  '/privacy': '2026-07-30',
  '/disclaimer': '2026-07-30',
  '/advertising': '2026-07-30',
  '/glossary': '2026-07-30',
  '/faq': '2026-07-30',
  '/security': '2026-07-30',
  '/editorial-policy': '2026-07-30',
  '/about': '2026-08-11',
  '/regulation': '2026-07-30',
};
