/**
 * The mark as it appears in the header and the footer — no tile.
 *
 * It used to be the mark PNG, the same square used for the favicon and the
 * app icon. That square carries a graphite tile, and the tile is #1D1D1F while
 * the site's own background is #1d1d1f — the same colour. On the dark theme the
 * tile was invisible, so a 40px box showed a 28px mark floating in 12px of
 * nothing. The tile belongs where the mark lands on someone else's background —
 * a favicon, an avatar, Google News — not here.
 *
 * The brackets take `currentColor`, so the mark follows the theme instead of
 * needing one file per background.
 *
 * The bolt's volume is two flat planes rather than a gradient. That is not a
 * simplification: the axis from the bolt's tip to its tail splits its six
 * vertices cleanly 2+2 without crossing an edge, so the lit face and the shaded
 * fold are each an ordinary polygon. No gradient, no clipPath, and — the part
 * that matters — no `id`, so the component can appear twice on a page and in a
 * server component without colliding with itself.
 */

/**
 * Corner brackets, replacing the two full-height plates.
 *
 * The plates measured 888 square units against the bolt's 200 — the frame
 * outweighed its contents 4.4 to 1, and the eye met two slabs before it met the
 * mark. These corners measure 140, so the bolt finally leads (0.70×).
 *
 * Each corner is two capsules, a reach across and a reach down, both fully
 * rounded. Capsules rather than a stroked path because brandMark.tsx draws the
 * same shape through Satori, whose rounded-rect support is complete where its
 * stroke support is not — and one geometry in both places is the whole point.
 *
 * Generated by ../../intokened.com/build-logo.py; regenerate rather than edit.
 */
const CAPSULES: ReadonlyArray<readonly [number, number, number, number]> = [
  [10.25, 9.25, 8.5, 3.5], [10.25, 9.25, 3.5, 8.5],
  [45.25, 9.25, 8.5, 3.5], [50.25, 9.25, 3.5, 8.5],
  [10.25, 51.25, 8.5, 3.5], [10.25, 46.25, 3.5, 8.5],
  [45.25, 51.25, 8.5, 3.5], [50.25, 46.25, 3.5, 8.5],
];
const R = 1.75;

/**
 * The face the light hits, and the one that turns away from it.
 *
 * These are the bolt at 0.66 — the size it is *inside the brackets*, which is
 * the only size it is ever drawn at here. Splitting the shape into two faces the
 * first time, I took the coordinates from the unscaled bolt and shipped a mark
 * 1.72× too large, which is exactly 1/0.58 for the scale then in use.
 *
 * Any change to BOLT_SCALE in build-logo.py has to be reflected here; these are
 * the same six vertices that file scales at runtime. Recomputing them by hand
 * is what caused that bug, so take them from the script rather than by eye.
 */
const BOLT_LIT = '37.28,14.84 21.44,34.64 30.68,34.64 26.72,49.16';
const BOLT_FOLD = '26.72,49.16 42.56,29.36 33.32,29.36 37.28,14.84';

const GOLD_LIT = '#FFC93C';
const GOLD_FOLD = '#D4820F';

/**
 * Cut to the drawing, not to the 64-unit square it is designed in.
 *
 * The old viewBox left 8.25 units of nothing on either side — 6.2px at header
 * size — so the word stood 11px from a bracket and more than half of that gap
 * was painted inside the picture rather than set in the layout. Hence also the
 * 45:47 aspect: callers set a height and let the width follow.
 */
const VIEW_BOX = '9.5 8.5 45 47';

export default function BrandMarkSvg({ className }: { className?: string }) {
  return (
    <svg viewBox={VIEW_BOX} className={className} aria-hidden="true" focusable="false">
      {CAPSULES.map(([x, y, w, h]) => (
        <rect key={`${x}-${y}-${w}`} x={x} y={y} width={w} height={h} rx={R} fill="currentColor" />
      ))}
      <polygon points={BOLT_LIT} fill={GOLD_LIT} />
      <polygon points={BOLT_FOLD} fill={GOLD_FOLD} />
    </svg>
  );
}
